#!/bin/bash

shopt -s expand_aliases
source ~/.bash_aliases

timestamp() {
	date +"%T"
}

notify=1
state="Topk" #Pulling Pushing"
time_step="0.01 0.1 1.0 5.0 10.0 15.0 20.0"
rate="BW" #HH-several Syn BW"
direction="Source" #Source Destination"
numHH="1" #8 9 10 11 12 5 6"
mechanism="prio" #table"
common_mask="1 2 4 8 16 32 64 128" #0 8 16 24 30"

for m in $mechanism; do
for s in $state; do
for r in $rate; do
for d in $direction; do
	time_stamp=`timestamp`
	folder_name="logs/${m}-${s}-${r}-${d}-"${time_stamp}
	mkdir -p ${folder_name}
	if [[ -d "logs/${m}-${s}-${r}-${d}/" ]]; then
		rm "logs/${m}-${s}-${r}-${d}"
	fi
	ln -s "../"${folder_name} "logs/${m}-${s}-${r}-${d}"
	for h in $numHH; do
	for ts in $time_step; do
	for c in $common_mask; do
		log_file="${folder_name}/${ts}-${h}-${c}.log"
		pcap_file="${folder_name}/${ts}-${h}-${c}.pcap"
		python ./src/SDM/scripts/ChangeConfig.py ${s} ${r} ${ts} ${d} ${h} ${m} ${c}
		tshark -i lo -w "${pcap_file}" &
		pid=$!
		sleep 10s
		PYTHONPATH=$PYTHONPATH ./src/SDM/scripts/run_env.py
	        kill -9 $pid
        	sleep 10s
		a=`grep "Alert!" ${log_file} | cut -d"(" -f2 | cut -d"," -f1 | uniq | wc -l`
		if [[ $a != $h ]]; then
			if [[ $notify != 0 ]]; then
				notify Failed-${ts}-${h}-${c}
			fi
			sleep 2m
			mn -c
			continue
		fi
		counters=`grep Maximal ${log_file} | rev | cut -d":" -f1 | rev`
		attack_start=`sed -n -e '/Attack started/,/Time step #/ p' ${log_file} | tail -1 | cut -d"#" -f2 | cut -d" " -f1`
	        alert_step=`tac ${log_file} | sed -n -e '/Alert/,/Time step #/ p' | tail -1 | cut -d"#" -f2 | cut -d" " -f1`
	        let steps=${alert_step}-${attack_start}
	        time=`echo ${steps}*${ts} | bc`
	        ofp_packets=`sudo tshark -2 -r ${pcap_file} -R "(openflow||openflow_v1||openflow_v4||openflow_v5) && ((tcp.srcport==6633) || (tcp.dstport==6633))" | wc -l`
	        echo ${time_stamp}: ${ts},${attack_start},${alert_step},${steps},${time},${ofp_packets},${h},${c},${counters} >> "logs/${m}-${s}-${r}-${d}.res"
		all_counters=`grep "counters" ${log_file} | cut -d":" -f3`
		arr_counters=($all_counters)
		all_steps=`grep "step" ${log_file} | cut -d"#" -f2 | cut -d" " -f1`
		arr_steps=($all_steps)
		total=${#arr_steps[*]}
		for (( i=${attack_start}-1; i<=$(( $total -1 )); i++ ))
		do
		    echo "${arr_steps[$i]}, ${arr_counters[i]}" >> "${folder_name}/${ts}-${h}-${c}.counters"
		done
		if [[ $notify != 0 ]]; then
		        notify Success-${ts}-${h}-${c}
		fi
	        sleep 2m
		mn -c
	done
	done
	done
done
done
done
done
