#!/bin/bash
shopt -s expand_aliases
source ~/.bash_aliases
for i in ./config/parameters*.cfg; do
	cp $i ./config/parameters.cfg
	base=`basename "${i}" | cut -d"." -f1`
	~/wireshark/tshark -i lo -w "./logs/${base}.pcap" &
	pid=$!
	PYTHONPATH=$PYTHONPATH ./src/SDM/scripts/run_env.py
	kill -9 $pid
	notify $i
done

