#!/bin/bash

# Creates secXX-groupedBy-YYCIDR.stat file which contains total bytecount per \YY CIDR group in the XX second.
# Since its a recording of 1 second thus it is equal to BW. The file is sorted by BW.

files="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59"
CIDRs="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32"
for i in $files; do
    cd ~/CAIDA-DLT/sec${i}/
    for c in $CIDRs; do
        groups=`echo "2^"${c} | bc`
        cat ./sec${i}.stat | awk -v g="$groups" 'BEGIN {
            FS=OFS=SUBSEP=" ";
            g1 = g > 256 ? 1 : g > 0 ? (256/g) : -1;
            g = int(g / 256); g2 = g > 256 ? 1 : g > 1 ? (256/g) : -1;
            g = int(g / 256); g3 = g > 256 ? 1 : g > 1 ? (256/g) : -1;
            g = int(g / 256); g4 = g > 256 ? 1 : g > 1 ? (256/g) : -1;
        }
        {
            split($1,ipArr,".");
            if (g1 == -1) { q1="" } else { p1=ipArr[1]/g1; split(p1,p1Arr,"."); q1=p1Arr[1];}
            if (g2 == -1) { q2="" } else { p2=ipArr[2]/g2; split(p2,p2Arr,"."); q2=p2Arr[1];}
            if (g3 == -1) { q3="" } else { p3=ipArr[3]/g3; split(p3,p3Arr,"."); q3=p3Arr[1];}
            if (g4 == -1) { q4="" } else { p4=ipArr[4]/g4; split(p4,p4Arr,"."); q4=p4Arr[1];}
            arr[q1"."q2"."q3"."q4]+=$2;
        }
        END {for (i in arr) print i, arr[i]}' | sort -n -r -k2 > ./sec${i}-groupedBy-${c}CIDR.stat
    done
    cd ..
done
