#!/bin/bash

while true
do
	tcpreplay -i h1-eth0 ~/tmp/sync.pcap
	tcpreplay -L 4 -i h1-eth0 ~/CAIDA-DLT/equinix-chicago.dirA.20140320-130000.UTC.anon.pcap
	sleep 0.1
done

#tcpreplay --pps=5 -i h1-eth0 ~/tmp/sync-attack.pcap

#tcpreplay -l 0 --pps=1 -i h1-eth0 ~/tmp/sync.pcap &
#pid_syn=$!
#tcpreplay -l 0 --pps=4 -i h1-eth0 ~/tmp/tcp.pcap
#tcpreplay --pps=5 -i h1-eth0 ~/CAIDA-DLT/equinix-chicago.dirA.20140320-130100.UTC.anon.pcap
#kill -9 $pid_syn
