#!/bin/bash

for ((i = 1; i <= $1; i++));
do
    cat client_"$i"_* | sort -n -s > client_"$i"_full_log
    rm -rf client_"$i"_Thread_*_log
    rm -rf client_"$i"_log

    cat server_"$i"_* | sort -n -s > server_"$i"_full_log
    rm -rf server_"$i"_Thread_*_log
    rm -rf server_"$i"_log

done
